// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: minimaltest.proto

package minimaltest

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_minimaltest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_minimaltest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_minimaltest_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPairRequest) Reset() {
	*x = PutPairRequest{}
	mi := &file_minimaltest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPairRequest) ProtoMessage() {}

func (x *PutPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minimaltest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPairRequest.ProtoReflect.Descriptor instead.
func (*PutPairRequest) Descriptor() ([]byte, []int) {
	return file_minimaltest_proto_rawDescGZIP(), []int{1}
}

func (x *PutPairRequest) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type GetPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairRequest) Reset() {
	*x = GetPairRequest{}
	mi := &file_minimaltest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairRequest) ProtoMessage() {}

func (x *GetPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minimaltest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairRequest.ProtoReflect.Descriptor instead.
func (*GetPairRequest) Descriptor() ([]byte, []int) {
	return file_minimaltest_proto_rawDescGZIP(), []int{2}
}

func (x *GetPairRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair" json:"pair,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_minimaltest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minimaltest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_minimaltest_proto_rawDescGZIP(), []int{3}
}

func (x *PairResponse) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *PairResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_minimaltest_proto protoreflect.FileDescriptor

var file_minimaltest_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c,
	0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x0e,
	0x50, 0x75, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x0c, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xa6, 0x01, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x54,
	0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1b,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x75, 0x74,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x69,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x69, 0x72, 0x12, 0x1b, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x09, 0x3a, 0x01, 0x2a, 0x22, 0x04, 0x2f, 0x67, 0x65, 0x74, 0x42, 0x18, 0x5a, 0x11,
	0x62, 0x69, 0x61, 0x64, 0x6f, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x73,
	0x74, 0x92, 0x03, 0x02, 0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x70, 0xe8, 0x07,
})

var (
	file_minimaltest_proto_rawDescOnce sync.Once
	file_minimaltest_proto_rawDescData []byte
)

func file_minimaltest_proto_rawDescGZIP() []byte {
	file_minimaltest_proto_rawDescOnce.Do(func() {
		file_minimaltest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_minimaltest_proto_rawDesc), len(file_minimaltest_proto_rawDesc)))
	})
	return file_minimaltest_proto_rawDescData
}

var file_minimaltest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_minimaltest_proto_goTypes = []any{
	(*Pair)(nil),           // 0: minimaltest.Pair
	(*PutPairRequest)(nil), // 1: minimaltest.PutPairRequest
	(*GetPairRequest)(nil), // 2: minimaltest.GetPairRequest
	(*PairResponse)(nil),   // 3: minimaltest.PairResponse
}
var file_minimaltest_proto_depIdxs = []int32{
	0, // 0: minimaltest.PutPairRequest.pair:type_name -> minimaltest.Pair
	0, // 1: minimaltest.PairResponse.pair:type_name -> minimaltest.Pair
	1, // 2: minimaltest.MinimalTest.PutPair:input_type -> minimaltest.PutPairRequest
	2, // 3: minimaltest.MinimalTest.GetPair:input_type -> minimaltest.GetPairRequest
	3, // 4: minimaltest.MinimalTest.PutPair:output_type -> minimaltest.PairResponse
	3, // 5: minimaltest.MinimalTest.GetPair:output_type -> minimaltest.PairResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_minimaltest_proto_init() }
func file_minimaltest_proto_init() {
	if File_minimaltest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minimaltest_proto_rawDesc), len(file_minimaltest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minimaltest_proto_goTypes,
		DependencyIndexes: file_minimaltest_proto_depIdxs,
		MessageInfos:      file_minimaltest_proto_msgTypes,
	}.Build()
	File_minimaltest_proto = out.File
	file_minimaltest_proto_goTypes = nil
	file_minimaltest_proto_depIdxs = nil
}
